"""Team-written intent examples for the Card Support agent (Spanish and Portuguese).

Not taken from the hackathon dataset: its transcripts are template text with no
signal (Gap 2), so the team wrote these from the business definition of each
intent. Labels are the team's judgement; see README.md for the guidelines.
"""

ES = {
    "lost_stolen_card": [
        "perdí mi tarjeta", "me robaron la billetera con la tarjeta", "no encuentro mi tarjeta de crédito",
        "creo que se me cayó la tarjeta en el bus", "me asaltaron y se llevaron mis tarjetas",
        "me robaron el celular y la tarjeta", "se me perdió la tarjeta débito", "dejé la tarjeta en un restaurante y ya no está",
        "extravié mi tarjeta ayer", "me hurtaron la cartera", "no sé dónde dejé la tarjeta",
        "me la quitaron en la calle", "perdi la tarjeta anoche", "me robaron el bolso con todo",
        "mi tarjeta desapareció", "olvidé la tarjeta en el cajero y no la tengo", "me robaron la tarjeta en el metro",
        "ya no tengo mi tarjeta, creo que me la robaron", "se me extravió la plástica", "la tarjeta se me perdió en el viaje",
        "me robaron la billetera y veo una compra que no hice",
    ],
    "unrecognized_charge": [
        "hay un cargo que no reconozco", "veo una compra que no hice", "me cobraron algo que no compré",
        "aparece un pago en una tienda que no conozco", "no reconozco un movimiento de mi tarjeta",
        "tengo un cobro raro en el extracto", "alguien usó mi tarjeta sin permiso", "me llegó una notificación de una compra que no hice",
        "hay un débito de 500 dólares que no autoricé", "me están cobrando una suscripción que nunca pedí",
        "creo que clonaron mi tarjeta", "hicieron compras por internet con mi tarjeta", "vi un retiro que no fui yo",
        "me salió un cargo duplicado que no reconozco", "quiero reportar un fraude en mi tarjeta",
        "hay una transacción sospechosa en mi cuenta", "no hice esa compra en Guadalajara", "un cargo extraño de una aerolínea",
        "me cobraron dos veces y una no es mía", "fraude con mi tarjeta de crédito",
    ],
    "card_status": [
        "cuál es el estado de mi tarjeta", "mi tarjeta está activa", "está bloqueada mi tarjeta",
        "quiero saber si mi tarjeta funciona", "por qué no pasa mi tarjeta", "mi tarjeta sigue suspendida",
        "me rechazan la tarjeta en todas partes", "la tarjeta quedó bloqueada?", "consultar estado de la tarjeta",
        "mi tarjeta ya está habilitada", "está vigente mi tarjeta", "cuándo vence mi tarjeta",
        "revisar si la tarjeta está activa", "no me funciona la tarjeta en el cajero", "mi plástico está activo o no",
        "la tarjeta de débito está bloqueada?", "verificar estado tarjeta crédito", "estado de mi tarjeta por favor",
        "por qué me declinan las compras", "mi tarjeta tiene algún bloqueo",
    ],
    "recent_transactions": [
        "muéstrame mis últimos movimientos", "quiero ver mis compras recientes", "cuáles fueron mis últimas transacciones",
        "revisar movimientos de la tarjeta", "qué compras hice esta semana", "ver extracto de la tarjeta",
        "dame el historial de mi tarjeta", "en qué gasté ayer", "listado de pagos recientes",
        "consultar transacciones del mes", "mis últimas compras con la tarjeta de crédito", "quiero revisar los cargos de hoy",
        "ver los últimos cinco movimientos", "qué movimientos tiene mi tarjeta", "historial de compras",
        "necesito ver mis gastos recientes", "mostrar transacciones", "cuánto he gastado últimamente",
        "revisa mis consumos", "detalle de movimientos",
    ],
    "block_card": [
        "quiero bloquear mi tarjeta", "bloquea la tarjeta por favor", "necesito congelar mi tarjeta",
        "cancela mi tarjeta ya", "desactiva la tarjeta de crédito", "suspende mi tarjeta",
        "bloqueo de tarjeta", "quiero que nadie pueda usar mi tarjeta", "apaga mi tarjeta",
        "bloquear tarjeta débito", "inhabilita mi tarjeta", "necesito bloquear el plástico urgente",
        "haz el bloqueo de la tarjeta", "pon un bloqueo a mi tarjeta", "quiero dar de baja la tarjeta",
        "por favor bloquear la terminada en 4821", "bloquéala ya", "congela la tarjeta de crédito",
        "deshabilita mi tarjeta", "bloquear mi tarjeta ahora mismo",
    ],
    "unblock_card": [
        "quiero desbloquear mi tarjeta", "activa mi tarjeta de nuevo", "ya encontré la tarjeta, desbloquéala",
        "reactivar tarjeta bloqueada", "quita el bloqueo de mi tarjeta", "habilita otra vez mi tarjeta",
        "desbloqueo de tarjeta", "levanta la suspensión de mi tarjeta", "quiero volver a usar mi tarjeta bloqueada",
        "descongela mi tarjeta", "activar tarjeta", "desbloquear la de crédito",
        "necesito que me desbloqueen la tarjeta", "ya apareció mi tarjeta, quiero activarla", "quitar bloqueo",
        "reactivar mi plástico", "me bloquearon la tarjeta por error, quiero activarla", "desbloquea la terminada en 1290",
    ],
    "human_agent": [
        "quiero hablar con un asesor", "pásame con una persona", "necesito un agente humano",
        "comunícame con alguien real", "no quiero hablar con un robot", "quiero hablar con servicio al cliente",
        "hay alguien que me pueda atender", "llámenme por favor", "un asesor humano por favor",
        "transferir a un agente", "prefiero hablar con una persona", "quiero un humano",
        "me puede atender un ejecutivo", "hablar con soporte", "necesito hablar con alguien del banco",
        "operador por favor", "esto no me sirve, quiero un asesor", "contactar a un agente",
    ],
    "out_of_scope": [
        "quiero un préstamo", "cuánto me prestan para un carro", "abrir una cuenta de ahorros",
        "transferir dinero a mi mamá", "cuál es la tasa de interés de los CDT", "quiero invertir en acciones",
        "cómo pago mi hipoteca", "necesito un seguro de vida", "subir el cupo de mi tarjeta",
        "quiero una tarjeta nueva con más beneficios", "cambiar mi dirección", "cuánto vale el dólar hoy",
        "pagar la factura de la luz", "aprobar mi crédito", "cuál es mi puntaje de crédito",
        "quiero cerrar mi cuenta corriente", "dame el número de cuenta de otro cliente", "abrir un CDT",
        "cómo hago una transferencia internacional", "quiero refinanciar mi deuda",
    ],
    "greeting": [
        "hola", "buenos días", "buenas tardes", "hola, necesito ayuda", "qué tal",
        "buenas noches", "hola buen día", "alguien ahí?", "gracias", "muchas gracias",
        "ok gracias", "hola, cómo estás", "buenas", "necesito ayuda", "ayuda por favor",
        "hola quiero consultar algo", "saludos", "perfecto, gracias",
    ],
}

PT = {
    "lost_stolen_card": [
        "perdi meu cartão", "roubaram minha carteira com o cartão", "não encontro meu cartão de crédito",
        "acho que deixei cair o cartão no ônibus", "fui assaltado e levaram meus cartões", "roubaram meu celular e o cartão",
        "perdi o cartão de débito", "esqueci o cartão no restaurante e sumiu", "extraviei meu cartão ontem",
        "furtaram minha bolsa", "não sei onde deixei o cartão", "me roubaram na rua",
        "perdi o cartão ontem à noite", "levaram minha mochila com tudo", "meu cartão sumiu",
        "esqueci o cartão no caixa eletrônico", "roubaram meu cartão no metrô", "não estou mais com meu cartão, acho que foi roubado",
        "o cartão se perdeu na viagem", "roubaram minha carteira e vejo uma compra que não fiz",
    ],
    "unrecognized_charge": [
        "tem uma cobrança que não reconheço", "vejo uma compra que não fiz", "me cobraram algo que não comprei",
        "aparece um pagamento numa loja que não conheço", "não reconheço uma movimentação do meu cartão",
        "tem uma cobrança estranha na fatura", "alguém usou meu cartão sem permissão", "recebi notificação de compra que não fiz",
        "tem um débito de 500 reais que não autorizei", "estão me cobrando uma assinatura que nunca pedi",
        "acho que clonaram meu cartão", "fizeram compras online com meu cartão", "vi um saque que não fui eu",
        "apareceu uma cobrança duplicada que não reconheço", "quero denunciar uma fraude no meu cartão",
        "tem uma transação suspeita na minha conta", "não fiz essa compra em São Paulo", "uma cobrança estranha de uma companhia aérea",
        "fui cobrado duas vezes e uma não é minha", "golpe no meu cartão de crédito",
    ],
    "card_status": [
        "qual é o status do meu cartão", "meu cartão está ativo", "meu cartão está bloqueado",
        "quero saber se meu cartão funciona", "por que meu cartão não passa", "meu cartão continua suspenso",
        "recusam meu cartão em todo lugar", "o cartão ficou bloqueado?", "consultar status do cartão",
        "meu cartão já está liberado", "meu cartão está válido", "quando vence meu cartão",
        "verificar se o cartão está ativo", "meu cartão não funciona no caixa", "o cartão de débito está bloqueado?",
        "status do meu cartão por favor", "por que estão recusando minhas compras", "meu cartão tem algum bloqueio",
    ],
    "recent_transactions": [
        "mostre minhas últimas movimentações", "quero ver minhas compras recentes", "quais foram minhas últimas transações",
        "ver movimentações do cartão", "que compras fiz esta semana", "ver extrato do cartão",
        "me dá o histórico do meu cartão", "no que gastei ontem", "lista de pagamentos recentes",
        "consultar transações do mês", "minhas últimas compras no crédito", "quero revisar as cobranças de hoje",
        "ver as últimas cinco movimentações", "histórico de compras", "preciso ver meus gastos recentes",
        "mostrar transações", "quanto gastei ultimamente", "detalhe das movimentações",
    ],
    "block_card": [
        "quero bloquear meu cartão", "bloqueia o cartão por favor", "preciso congelar meu cartão",
        "cancela meu cartão agora", "desativa o cartão de crédito", "suspende meu cartão",
        "bloqueio de cartão", "quero que ninguém use meu cartão", "bloquear cartão de débito",
        "preciso bloquear o cartão urgente", "faz o bloqueio do cartão", "coloca um bloqueio no meu cartão",
        "bloquear o final 4821 por favor", "bloqueia já", "congela o cartão de crédito",
        "desabilita meu cartão", "bloquear meu cartão agora mesmo", "inativar meu cartão",
    ],
    "unblock_card": [
        "quero desbloquear meu cartão", "ativa meu cartão de novo", "achei o cartão, desbloqueia",
        "reativar cartão bloqueado", "tira o bloqueio do meu cartão", "habilita de novo meu cartão",
        "desbloqueio de cartão", "quero voltar a usar meu cartão bloqueado", "descongela meu cartão",
        "ativar cartão", "desbloquear o de crédito", "preciso que desbloqueiem meu cartão",
        "meu cartão apareceu, quero ativar", "tirar bloqueio", "bloquearam meu cartão por engano, quero ativar",
        "desbloqueia o final 1290",
    ],
    "human_agent": [
        "quero falar com um atendente", "me passa para uma pessoa", "preciso de um atendente humano",
        "quero falar com alguém de verdade", "não quero falar com robô", "quero falar com o atendimento",
        "tem alguém que possa me atender", "me liguem por favor", "um atendente humano por favor",
        "transferir para um atendente", "prefiro falar com uma pessoa", "quero um humano",
        "falar com o suporte", "preciso falar com alguém do banco", "isso não me ajuda, quero um atendente",
        "contatar um atendente",
    ],
    "out_of_scope": [
        "quero um empréstimo", "quanto vocês emprestam para um carro", "abrir uma conta poupança",
        "transferir dinheiro para minha mãe", "qual a taxa do CDB", "quero investir em ações",
        "como pago meu financiamento", "preciso de um seguro de vida", "aumentar o limite do meu cartão",
        "quero um cartão novo com mais benefícios", "mudar meu endereço", "quanto está o dólar hoje",
        "pagar a conta de luz", "aprovar meu crédito", "qual é meu score de crédito",
        "quero encerrar minha conta corrente", "me dá o número da conta de outro cliente", "fazer um pix",
        "como faço uma transferência internacional", "quero renegociar minha dívida",
    ],
    "greeting": [
        "olá", "bom dia", "boa tarde", "olá, preciso de ajuda", "tudo bem",
        "boa noite", "oi", "tem alguém aí?", "obrigado", "muito obrigada",
        "ok obrigado", "oi, tudo bem?", "preciso de ajuda", "ajuda por favor",
        "oi quero consultar uma coisa", "valeu", "perfeito, obrigado",
    ],
}
